### ISSUE TITLE
Helm lint fails with 0.10.0+

### ISSUE THREAD

**Issue by NathanVaughn** [kubetail-org/helm-charts#105]
I've noticed that since version 0.10.0, `helm lint` fails.

To reproduce:

```bash
mkdir temp
cd temp
helm pull --repo https://kubetail-org.github.io/helm-charts/ --version 0.10.0 kubetail
helm lint kubetail-0.10.0.tgz
```

Output:

```text
==> Linting kubetail-0.10.0.tgz
[ERROR] templates/cluster-api/rbac.yaml: unable to parse YAML: invalid Yaml document separator: kind: Role

Error: 1 chart(s) linted, 1 chart(s) failed
```

I believe this was introduced by commit 6a53ddb39a3b0200f5ff3f3f784856f16aa851eb.

I have not tried applying this chart and seeing if it works still.

**Comment by amorey** [comment]
Working on it.

**Comment by amorey** [comment]
Thanks for letting us know about the problem. I fixed the issue causing the linting error and added a linting check to the CI workflow so we can prevent this from happening again in the future. Ironically, my first attempt at fixing the linting issue introduced another error that the linter didn't pick up on but that's fixed too.

Quick question - I'm debating removing the top-level "kubetail" specifier from values.yaml. Currently it looks like this:

```yaml
fullnameOverride: null
nameOverride: null
namespaceOverride: null

kubetail:
  allowedNamespaces: []

  global:
    annotations: {}
    labels: {}

  dashboard:
    enabled: true

...
```

And if we make the change it will look like this:

```yaml
fullnameOverride: null
nameOverride: null
namespaceOverride: null

allowedNamespaces: []

global:
  annotations: {}
  labels: {}

dashboard:
  enabled: true

...
```

Do you have a preference?
