### ISSUE TITLE
ingress 404 not found

### ISSUE THREAD

**Issue by nodesocket** [kubetail-org/helm-charts#40]
@amorey I switched to the new helm repo addr and upgrade to the latest chart and version. Unfortunately, when I navigate to my `ingress` host I am getting `404 page not found`.

Below is my full `values.yaml`:

```yaml
kubetail:
  podTemplate:
    resources:
      requests:
        cpu: 250m
        memory: 64Mi
      limits:
        cpu: 1
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls.certresolver: le
    rules:
    - host: kubetail.mydomain.com
      paths:
      - path: /
        pathType: Prefix
    tls:
    - hosts:
      - kubetail.mydomain.com
```

**Comment by amorey** [comment]
Sorry about the `404` issue. Here are the old/new `Ingress` manifests:

Old:
```yaml
# Source: kubetail/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubetail
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: le
spec:
  rules:
  - host: kubetail.mydomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kubetail
            port:
              number: 4000
  tls:
  - hosts:
    - kubetail.mydomain.com
    secretName: kubetail
```

New:
```yaml
# Source: kubetail/templates/ingress.yaml
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: kubetail
  namespace: kubetail
  labels:
    helm.sh/chart: kubetail-0.4.4
    app.kubernetes.io/name: kubetail
    app.kubernetes.io/instance: kubetail
    app.kubernetes.io/version: "0.4.6"
    app.kubernetes.io/managed-by: Helm
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: le
spec:
  rules:
  - host: kubetail.mydomain.com
    paths:
    - path: /
      pathType: Prefix
  tls:
  - hosts:
    - kubetail.mydomain.com
```

The main differences are:
1. the new resource is namespaced
2. the new resource is missing the `secretName` attribute under `tls` settings

The new chart creates a `Secret` resource named `kubetail` for config secrets so it's possible that the new resource might have overwritten your old resource that you were using for the Ingress's tls secret. Try creating a tls secret and adding a reference to it in your `values.yaml` file (e.g. `kubetail-cert`):

```yaml
kubetail:
  podTemplate:
    resources:
      requests:
        cpu: 250m
        memory: 64Mi
      limits:
        cpu: 1
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls.certresolver: le
    rules:
    - host: kubetail.mydomain.com
      paths:
      - path: /
        pathType: Prefix
    tls:
    - hosts:
      - kubetail.mydomain.com
      secretName: kubetail-cert
```

Let me know if that helps.

**Comment by nodesocket** [comment]
Adding `secretName` did not help. The SSL certificate is valid and being created by Let's Encrypt, but it seems to be a path issue. Still getting `404 not found` when hitting the host `https://kubetail.mydomain.com`.

```
$ kubectl describe ingress kubetail
Name:             kubetail
Labels:           app.kubernetes.io/instance=kubetail
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=kubetail
                  app.kubernetes.io/version=0.4.6
                  helm.sh/chart=kubetail-0.4.4
Namespace:        default
Address:
Ingress Class:    traefik
Default backend:  <default>
TLS:
  kubetail-cert terminates kubetail.mydomain.com
Rules:
  Host        Path  Backends
  ----        ----  --------
  *           *     <default>
Annotations:  meta.helm.sh/release-name: kubetail
              meta.helm.sh/release-namespace: default
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              traefik.ingress.kubernetes.io/router.tls: true
              traefik.ingress.kubernetes.io/router.tls.certresolver: le
Events:       <none>
```

**Comment by amorey** [comment]
Sorry, I'm just seeing it now but the other thing that's missing from the new `Ingress` resource is the `backend` declaration under `rules`. Try this for your `values.yaml` file (note that I replaced the port number with a name and kept secretName kubernetes-cert):

```yaml
kubetail:
  podTemplate:
    resources:
      requests:
        cpu: 250m
        memory: 64Mi
      limits:
        cpu: 1
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls.certresolver: le
    rules:
    - host: kubetail.mydomain.com
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kubetail
            port:
              name: kubetail
    tls:
    - hosts:
      - kubetail.mydomain.com
      secretName: kubetail-cert
```

**Comment by nodesocket** [comment]
still the same `404 page not found`. Here are describes on both the service and ingress. This used to work, so something changed.

```
$ kubectl describe service kubetail
Name:              kubetail
Namespace:         default
Labels:            app.kubernetes.io/instance=kubetail
                   app.kubernetes.io/managed-by=Helm
                   app.kubernetes.io/name=kubetail
                   app.kubernetes.io/version=0.4.6
                   helm.sh/chart=kubetail-0.4.4
Annotations:       meta.helm.sh/release-name: kubetail
                   meta.helm.sh/release-namespace: default
Selector:          app.kubernetes.io/instance=kubetail,app.kubernetes.io/name=kubetail
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.96.9.229
IPs:               10.96.9.229
Port:              kubetail  80/TCP
TargetPort:        80/TCP
Endpoints:         10.244.2.185:80
Session Affinity:  None
Events:            <none>
```

```
$ kubectl describe ingress kubetail
Name:             kubetail
Labels:           app.kubernetes.io/instance=kubetail
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=kubetail
                  app.kubernetes.io/version=0.4.6
                  helm.sh/chart=kubetail-0.4.4
Namespace:        default
Address:
Ingress Class:    traefik
Default backend:  <default>
TLS:
  kubetail-cert terminates kubetail.mecasa.dev
Rules:
  Host        Path  Backends
  ----        ----  --------
  *           *     <default>
Annotations:  meta.helm.sh/release-name: kubetail
              meta.helm.sh/release-namespace: default
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              traefik.ingress.kubernetes.io/router.tls: true
              traefik.ingress.kubernetes.io/router.tls.certresolver: le
Events:       <none>
```

**Comment by amorey** [comment]
Ok, I'll try something else. In the mean time, can you tear down the chart and install it again? The ingress description lists `<default>` as the backend but I would have expected it to show the kubetail service as the backend.

**Comment by amorey** [comment]
Also, I just noticed that `paths` should be nested under `http`. Try this:
```yaml
kubetail:
  podTemplate:
    resources:
      requests:
        cpu: 250m
        memory: 64Mi
      limits:
        cpu: 1
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls.certresolver: le
    rules:
    - host: kubetail.mydomain.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: kubetail
              port:
                name: kubetail
    tls:
    - hosts:
      - kubetail.mydomain.com
      secretName: kubetail-cert
```

**Comment by nodesocket** [comment]
@amorey still getting `404 page not found`. Let me know what else you need to help debug this.

**Comment by amorey** [comment]
Sorry about that and thanks for your patience. 🙏

I think I figured it out... the last change fixed the issue with the `Ingress` but there was a bug in the `Service` that was causing the `Bad Gateway` error (the `targetPort` was missing from the `Service` template). I fixed that bug in the latest chart and also re-implemented the Ingress `backend` definition logic from your original template so you no longer have to define it in your values file.

Try upgrading to the latest chart (0.4.5) and using these values:
```yaml
kubetail:
  podTemplate:
    resources:
      requests:
        cpu: 250m
        memory: 64Mi
      limits:
        cpu: 1
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls.certresolver: le
    rules:
    - host: kubetail.mydomain.com
      http:
        paths:
        - path: /
          pathType: Prefix
    tls:
    - hosts:
      - kubetail.mydomain.com
      secretName: kubetail-cert
```

I think that should work. 🤞 Let me know!

**Comment by nodesocket** [comment]
@amorey great success that worked. Thanks for all the help. 🙏🏻

**Comment by amorey** [comment]
Awesome! Thanks for your help debugging it!

**Comment by amorey** [comment]
@nodesocket Just a quick update - I released a new version yesterday (0.7.0) that gives you a birds eye view of log sizes and event frequencies across the entire cluster. Here's a live demo:
https://demo.kubetail.com

I had to make some changes to the [values.yaml](https://github.com/kubetail-org/helm-charts/blob/main/charts/kubetail/values.yaml) schema so you'll need to update your values.yaml file to upgrade. Let me know if you need help or if you run into trouble.

**Comment by nodesocket** [comment]
Hi @amorey. Awesome to see progress of kubetail progressing. 

What are the breaking changes? Here is my current `values.yaml`:

```yaml
kubetail:
  podTemplate:
    resources:
      requests:
        cpu: 250m
        memory: 64Mi
      limits:
        cpu: 1
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls.certresolver: le
    rules:
    - host: kubetail.mydomain.com
      http:
        paths:
        - path: /
          pathType: Prefix
    tls:
    - hosts:
      - kubetail.mydomain.com
      secretName: kubetail-cert
```
